spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: publisher
    password: publisher
    virtual-host: /
  profiles:
    active: native
  application:
    name: spring-config
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    static-locations: /
  cloud:
      config:
        server:
          git:
            uri: https://github.com/cby86/cloud.git
            username:
            password:
            search-paths: config/{application}
            default-label: optimize
          native:
            search-locations: file:F:/project/cloud/config/{application}/
            default-label:
      bus:
        trace:
          enabled: true
        refresh:
          enabled: false  # 不采用系统默认的，因为所有的更新消息分发点都在config,如果要刷新其他服务,本地事件也会监听，导致重启config
      stream:
        rabbit:
          default:
            consumer:
              anonymousGroupPrefix: ${spring.application.name}.${server.port}. #配置队列名称
  security:
    basic:
      enabled: true               # 开启基于HTTP basic的认证
    user:
      name: user                  # 配置登录的账号是user
      password: password123
server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/
    security:
      basic:
        user: user
        password: password123
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'


