spring:
  rabbitmq:
     publisher-confirms: true
  cloud:
    stream:
      bindings:
         output:
           destination: bussinessMessage
           producer:
              errorChannelEnabled: true #生产者发布错误回调启用
         input:
           destination: bussinessMessage
           group: ${spring.application.name}
      rabbit:
         bindings:
            output:
               producer:
                  confirmAckChannel: bussinessMessageConfirm
                  routing-key-expression: headers.messageType
            input:
               consumer:
                 bindingRoutingKey: "*.resource.*"
                 acknowledge-mode: manual
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 5
      max-idle: 2
      initialization-mode: NEVER
      min-idle: 1
      initial-size: 1
      test-while-idle: true
      test-on-borrow: false
      time-between-eviction-runs-millis: 18800
  jpa:
    database : MYSQL
    open-in-view: true
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate:
            format_sql: false
            use_sql_comments: true
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: com.spring.cloud.base.dialect.CustomerMysql5Dialect
