route:
    returnFailRoutePath: true
spring:
  cloud:
    stream:
       binders:
         business:
           type: rabbit
           environment:
             spring:
               rabbitmq:
                 host: localhost
                 port: 5672
                 username: publisher
                 password: publisher
                 virtual-host: /
       bindings:
          input:
            destination: bussinessMessage
       default:
          consumer:
              maxAttempts: 3
       rabbit:
         bindings:
           input:
              consumer:
                 bindingRoutingKey: "*.geteway.*"
                 autoBindDlq: true
                 republishToDlq: true
                 acknowledge-mode: manual
                 anonymousGroupPrefix: ${spring.application.name}.